### ISSUE TITLE
LisaNetForNodeI

### ISSUE THREAD

**Issue by pmarjora** [USCbiostats/PathwayAnalysis#2]
Check that code! It doesn't look right.

**Comment by pmarjora** [comment]
and add explanations of what is happening

**Comment by pmarjora** [comment]
@MingzhiYe16
Pleas see if the logic now makes sense to you.

**Comment by MingzhiYe16** [comment]
Yes, it makes sense.

**Comment by pmarjora** [comment]
GreaT! And you were right about the error in (global) Moran's-I, so thanks for that!
I have now fixed that problem.
